version: '3'

services:
  super_unko:
    build:
      context: ./
      dockerfile: ./build/super_unko/Dockerfile
    image: unkontributors/super_unko

  formatter:
    image: peterdavehello/shfmt
    container_name: formatter
    volumes:
      - "$PWD:/work"
    entrypoint:
      - "shfmt"
      - "-i"
      - "2"
      - "-ci"
      - "-sr"
      - "-d"

  linter:
    image: koalaman/shellcheck
    container_name: linter
    volumes:
      - "$PWD:/work"
    entrypoint:
      - "shellcheck"
